version: '3.8'
services:
  postgres:
    image: imresamu/postgis:15-3.4-bundle
    container_name: my_postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    networks:
      - my_network  # Add this line to connect to the custom network

  localstack:
      container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
      image: localstack/localstack
      ports:
        - "127.0.0.1:4566:4566"            # LocalStack Gateway
        - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      environment:
        # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
        - DEBUG=${DEBUG:-1}
      volumes:
        - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"
      networks:
        - my_network  # Add this line to connect to the custom network


  my_fastapi_app:
    build:
      context: . #Current Path
      dockerfile: Dockerfile  # Assuming your Dockerfile is named 'Dockerfile'
    container_name: iot_company_api
    ports:
      - "8000:80"
    networks:
      - my_network

volumes:
  pg_data:

networks:
  my_network: